### ISSUE TITLE
Bug: To Rigify is not working with Blender 4.0 and above

### ISSUE THREAD

**Issue by daz-ddb** [daz3d/DazToBlender#198]
To Rigify feature of DazToBlender is not compatible with Blender 4.0.  A update to fix this bug is on our todo list.

**Comment by McSimKammerer** [comment]
Hi!
Any chance to get fix for that bug soon?
Thank you for your work!

**Comment by totalvectors** [comment]
Just updating folks on this bug. Still happening for me on Blender 4.2. It spits out this error:

Python: Traceback (most recent call last):
  File "C:\Users\total\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\DTB\DtbOperators.py", line 600, in execute
    trf.toRigify(db, self)
  File "C:\Users\total\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\DTB\ToRigify.py", line 163, in toRigify
    self.omit_g8(db)
  File "C:\Users\total\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\DTB\ToRigify.py", line 248, in omit_g8
    self.to_layer(eb, 15)
  File "C:\Users\total\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\DTB\ToRigify.py", line 281, in to_layer
    ebone.layers[lnum] = True
    ^^^^^^^^^^^^
AttributeError: 'EditBone' object has no attribute 'layers'

It does manage to generate the Rigify rig but the control rig isn't parented to the mesh. I wonder if the new bone collections introduced in 4.0 have something to do with this issue.
